### ISSUE TITLE
What's the right way to compile it?

### ISSUE THREAD

**Issue by Zeioth** [VortexCoyote/hyprfocus#2]
If I just cloned this repo and run

    make all

I get the error 
```
g++ -shared -fPIC --no-gnu-unique main.cpp -o hyprfocus.so -g -I "/usr/include/pixman-1" -I "/usr/include/libdrm" -I "" -I "/subprojects/wlroots/include" -I "/subprojects/wlroots/include" -I "/subprojects/wlroots/build/include" -std=c++23
main.cpp:3:10: fatal error: src/plugins/PluginAPI.hpp: No such file or directory
    3 | #include <src/plugins/PluginAPI.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:6: all] Error 1
```
But if I do it like described [here](https://wiki.hyprland.org/Plugins/Using-Plugins/#compiling-official-plugins) I get this instead

```
HYPRLAND_HEADERS="../Hyprland" make all 
g++ -shared -fPIC --no-gnu-unique main.cpp -o hyprfocus.so -g -I "/usr/include/pixman-1" -I "/usr/include/libdrm" -I "../Hyprland" -I "../Hyprland/subprojects/wlroots/include" -I "../Hyprland/subprojects/wlroots/include" -I "../Hyprland/subprojects/wlroots/build/include" -std=c++23
In file included from ../Hyprland/src/defines.hpp:1,
                 from ../Hyprland/src/Window.hpp:3,
                 from main.cpp:7:
../Hyprland/src/includes.hpp:74:10: fatal error: wlr/types/wlr_output_damage.h: No such file or directory
   74 | #include <wlr/types/wlr_output_damage.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:6: all] Error 1
```

**Comment by Zeioth** [comment]
I managed to compile it yesterday. wlrooots was necessary (instead of wlroots-git). 

Failed to load with

    hyprctl plugin load ./hyprfocus.so
    error in loading plugin

Today is failing to compile with a different error:

    borderDeco.hpp:5:10: fatal error: hyprland/src/render/decorations/IHyprWindowDecoration.hpp: No such file or directory

I think I'm gonna wait until it stabilizes a bit.

**Comment by VortexCoyote** [comment]
im unable to compile it as well, and is a bit confused as to why. the hyprland source includes wlroots as a git submodule, but some files seems to be missing from wlroots. i'll look more into it

**Comment by VortexCoyote** [comment]
i got it. turns out i forgot how to compile plugins. here's the step by step instructions based [the official wiki](https://wiki.hyprland.org/Plugins/Using-Plugins/#compiling-official-plugins):

**1) clone hyprfocus and cd into it**

`git clone https://github.com/VortexCoyote/hyprfocus && cd hyprfocus`

**2) clone hyprland and cd into it**

`git clone --recursive https://github.com/hyprwm/Hyprland && cd Hyprland`

**3) you need to checkout the correct release tag to match with your version of hyprland.** in my case, i got the latest one so.

`git checkout tags/v0.24.1`

**4) prepare the hyprland source for plugin compilation**

`make pluginenv`

**5) cd back and make**

`cd .. && HYPRLAND_HEADERS="Hyprland/" make`

**6) profit**

`hyprctl plugin load <.so path>`


let me know if these steps works, i might add them to the readme file

**Comment by Zeioth** [comment]
It compiles correctly thank you!! but

    hyprctl plugin load hyprfocus.so

fails with "error in loading.

```
hyprctl version
Hyprland, built from branch main at commit f23455e592bca14e0abd9249de467cc71cd2850e dirty (makefile: use -f in copies to avoid errors on running hl).
Tag: v0.24.1-112-gf23455e5

flags: (if any)
```

**Comment by VortexCoyote** [comment]
could you try using the full path to the .so file?

**Comment by Zeioth** [comment]
Using the absolute path seems works ok!!

    hyprctl plugin load /home/zeioth/.local/share/hyprfocus/hyprfocus.so     
    ok

But the plugin does nothing. If I try to enable it on hyprland config like

```
plugin:hyprfocus {
    enabled = yes
}
```
Hyprlad complains there is no such field as plugin:hyprfocus

**Comment by Zeioth** [comment]
The specific error hyprland displays is 

    Error setting <true> for field <master:gestures:plugin:hyprfocus:enabled>:No such field.

**Comment by VortexCoyote** [comment]
could you show me your config file/s? the "plugin:plugin:hyprfocus" looks weird to me

**Comment by Zeioth** [comment]
yes you have them online here: https://github.com/Zeioth/zeioth-hyprland-config/blob/main/config.d/03-hyprland-plugins

EDIT: That was a typo sorry. But same error.
![screenshot_2023-04-28_15-20-06_616997847](https://user-images.githubusercontent.com/3357792/235158563-2028b0a9-23f6-4c13-b389-b9642f27a8f2.png)

**Comment by VortexCoyote** [comment]
so several things to try here;

1) im not seeing you source [02-hyprland-plugins.conf](https://github.com/Zeioth/zeioth-hyprland-config/blob/main/autostart.d/02-hyprland-plugins.conf) in the main config file, which is probably necessary

2) i dont know if this is the case, but i think the plugin needs to be loaded _before_ you configure it (as it declares config variables and such)

3) it might be worth trying to just do it bare bones in the main config file, since i dont know how sourcing reacts with the plugin system

**Comment by Zeioth** [comment]
It seems to be failing to compile again. I've done:

* Now git checkout tags/v0.25.0 is used (hypaland-git)
* make pluginenv → now requires sudo permissions

Output:

```
 "Hyprland//subprojects/wlroots/include" -I "Hyprland//subprojects/wlroots/build/include" -std=c++23
In file included from Hyprland/src/includes.hpp:53,
                 from Hyprland/src/defines.hpp:1,
                 from Hyprland/src/Window.hpp:3,
                 from main.cpp:7:
Hyprland//subprojects/wlroots/include/wlr/types/wlr_layer_shell_v1.h:16:10: fatal error: wlr-layer-shell-unstable-v1-protocol.h: No such file or directory
   16 | #include "wlr-layer-shell-unstable-v1-protocol.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:6: all] Error 1
```

But your latest comment made sense to me. I'm gonna re-test as soon as I can compile again. Testing is difficult with so many quick changes, but that's a good thing in the long term most likely 😄

Edit: [Config updated to exec the plugin before trying to apply settings](https://github.com/Zeioth/zeioth-hyprland-config/blob/main/hyprland.conf).

**Comment by vaxerski** [comment]
plugin needs to be updated to work with 0.25.0 onwards.

**Comment by vaxerski** [comment]
I made #3

**Comment by VortexCoyote** [comment]
merged, keeping issue open until Zeioth reports back

**Comment by Zeioth** [comment]
It compiles and loads correctly again on v0.25.0

But still fails to detect [my settings](https://github.com/Zeioth/zeioth-hyprland-config/blob/main/config.d/03-hyprland-plugins) → loaded [here](https://github.com/Zeioth/zeioth-hyprland-config/blob/main/hyprland.conf)
![screenshot_2023-05-24_00-12-10_419207057](https://github.com/VortexCoyote/hyprfocus/assets/3357792/89e75d9f-28ee-4649-a711-6f1d72bbbfe0)

**Comment by vaxerski** [comment]
obviously because you are defining them in `master:gestures`?

**Comment by vaxerski** [comment]
your config is full of invalid syntax occurrences:

![image](https://github.com/VortexCoyote/hyprfocus/assets/43317083/5dbb0fcf-3aa5-4c59-bcdb-5b69bdacb49a)

![image](https://github.com/VortexCoyote/hyprfocus/assets/43317083/380cc6b7-f68c-4437-863f-af9ca53b81d6)
